name: hds_logistics
channels:
  - conda-forge
dependencies:
  - contextily=1.6.0
  - folium=0.17.0
  - geopandas=1.0.1
  - geoplot=0.5.1
  - jupyterlab=4.4.7
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.9.1
  - numpy=2.0.1
  - pandas=2.2.2
  - pip=24.0
  - pysal=23.7
  - python=3.11
  - scipy=1.14.0
  - seaborn=0.13.2
